# Generated by Django 3.0.6 on 2020-12-23 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='送信日時'),
        ),
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(default='title', max_length=50, verbose_name='件名'),
        ),
    ]
