# Generated by Django 3.0.6 on 2020-12-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_auto_20201223_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postidea',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='期日'),
        ),
    ]
