# Generated by Django 3.0.6 on 2020-12-26 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_auto_20201226_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('recruitment_id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=50, verbose_name='募集中の人材')),
                ('number', models.IntegerField(verbose_name='募集人数')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.PostIdea', verbose_name='募集中のアイデア')),
            ],
        ),
    ]
