# Generated by Django 3.0.6 on 2021-01-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_recruitment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postidea',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='postidea',
            name='feedback_point',
        ),
        migrations.RemoveField(
            model_name='postidea',
            name='offer',
        ),
    ]
